require("plugins.catppuccin")
require("plugins.snacks")
require("plugins.lualine")
require("plugins.mini")
require("plugins.nvim-tree")
require("plugins.flash")
require("plugins.grug-far")

require("plugins.todo-comments")
require("plugins.colorizer")

require("plugins.treesitter")
require("plugins.lsp")
require("plugins.outline")
require("plugins.conform")
require("plugins.lint")
require("plugins.blink")

require("plugins.diffview")
require("plugins.gitsigns")
